/**
 * Next.js Proxy (formerly middleware) — Auth and Security Headers
 *
 * Runs before every matched request to:
 *  1. Refresh the Supabase session transparently (Req 8.9)
 *  2. Redirect unauthenticated visitors away from /admin/** (Req 8.8)
 *  3. Set security headers on every response (Req 15.1–15.5, 15.8)
 *
 * NOTE: In Next.js 16, the middleware file convention was renamed from
 * `middleware.ts` to `proxy.ts` and the exported function from `middleware`
 * to `proxy`. All functionality is identical.
 *
 * Requirements: 8.8, 8.9, 15.1, 15.2, 15.3, 15.4, 15.5, 15.8
 */

import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

// ---------------------------------------------------------------------------
// Content Security Policy
// ---------------------------------------------------------------------------

/**
 * Builds the Content-Security-Policy header value for a given per-request
 * nonce.  The nonce is embedded in the `script-src` and `style-src`
 * directives so that inline scripts/styles generated by the application are
 * allowed while third-party injections are blocked (Req 15.1, 15.8).
 *
 * @param nonce - A per-request random value, base64-encoded.
 */
export function buildCSP(nonce: string): string {
  const isDev = process.env.NODE_ENV !== 'production';

  // Allow hot-reload WebSocket in dev; block eval in production.
  const scriptSrc = isDev
    ? `'self' 'nonce-${nonce}' 'unsafe-eval'`
    : `'self' 'nonce-${nonce}'`;

  // Allow Tailwind's runtime styles in dev; lock down in prod.
  const styleSrc = isDev
    ? `'self' 'nonce-${nonce}' 'unsafe-inline'`
    : `'self' 'nonce-${nonce}'`;

  // Supabase endpoint — derived from env var if present so the policy works
  // for both local (http://127.0.0.1:54321) and cloud (*.supabase.co) setups.
  const supabaseHost = process.env.NEXT_PUBLIC_SUPABASE_URL
    ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).host
    : '*.supabase.co';

  const directives: Record<string, string> = {
    'default-src': "'self'",
    'script-src': scriptSrc,
    'style-src': styleSrc,
    // Images served by Next.js image optimisation plus Supabase Storage.
    'img-src': `'self' data: blob: https://${supabaseHost}`,
    // Fonts — none loaded from third-party CDNs; local only.
    'font-src': "'self'",
    // API and auth calls go to Supabase.
    'connect-src': `'self' https://${supabaseHost}`,
    // No iframes, objects, or plugins.
    'frame-src': "'none'",
    'object-src': "'none'",
    'base-uri': "'self'",
    // Upgrade insecure requests in production.
    ...(isDev ? {} : { 'upgrade-insecure-requests': '' }),
  };

  return Object.entries(directives)
    .map(([key, value]) => (value ? `${key} ${value}` : key))
    .join('; ');
}

// ---------------------------------------------------------------------------
// Proxy function (formerly middleware)
// ---------------------------------------------------------------------------

export async function proxy(request: NextRequest) {
  // Start building the response — we need it early to set cookies from the
  // Supabase SSR library when a token refresh occurs.
  const response = NextResponse.next({
    request,
  });

  // -------------------------------------------------------------------------
  // 1. Refresh the Supabase session transparently (Req 8.9)
  //    `supabase.auth.getUser()` validates the access token and, when it has
  //    expired, silently exchanges the refresh token for a new pair.  The new
  //    tokens are written back via `setAll` below.
  // -------------------------------------------------------------------------
  const supabaseUrl =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseAnonKey =
    process.env.SUPABASE_ANON_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseAnonKey) {
    // Environment not configured — skip Supabase work to avoid a hard crash
    // during local dev before .env.local is set up, but still apply headers.
    console.warn(
      '[proxy] Missing SUPABASE_URL / SUPABASE_ANON_KEY — skipping session refresh.',
    );
    return applySecurityHeaders(response, request);
  }

  const isProduction = process.env.NODE_ENV === 'production';

  const supabase = createServerClient(supabaseUrl, supabaseAnonKey, {
    cookieOptions: {
      httpOnly: true,
      secure: isProduction,
      sameSite: 'lax' as const,
      path: '/',
    },
    cookies: {
      getAll() {
        return request.cookies.getAll();
      },
      setAll(cookiesToSet) {
        // Write updated tokens to both the mutated request object and the
        // response so that downstream Server Components see the fresh session
        // AND the browser receives the Set-Cookie header.
        cookiesToSet.forEach(({ name, value }) => {
          request.cookies.set(name, value);
        });
        cookiesToSet.forEach(({ name, value, options }) => {
          response.cookies.set(name, value, options);
        });
      },
    },
  });

  // Calling getUser() triggers the transparent token refresh described above.
  const {
    data: { user },
  } = await supabase.auth.getUser();

  // -------------------------------------------------------------------------
  // 2. Protect /admin/** routes — redirect unauthenticated requests (Req 8.8)
  // -------------------------------------------------------------------------
  if (request.nextUrl.pathname.startsWith('/admin')) {
    if (!user) {
      const loginUrl = new URL('/auth/login', request.url);
      loginUrl.searchParams.set('redirectTo', request.nextUrl.pathname);
      return NextResponse.redirect(loginUrl);
    }
  }

  // -------------------------------------------------------------------------
  // 3. Set security headers (Req 15.1–15.5, 15.8)
  // -------------------------------------------------------------------------
  return applySecurityHeaders(response, request);
}

/**
 * Mutates the given response by setting all required security headers and
 * forwarding the per-request nonce via `x-nonce` so that layout.tsx can
 * inject it into `<script nonce>` tags (Req 15.8).
 */
function applySecurityHeaders(
  response: NextResponse,
  request: NextRequest,
): NextResponse {
  // Generate a fresh per-request nonce.  crypto.randomUUID() is available in
  // the Node.js runtime and the Edge runtime.
  const nonce = Buffer.from(crypto.randomUUID()).toString('base64');

  // Pass the nonce downstream so Server Components can use it for inline
  // scripts/styles (set as a request header so it is available via headers()).
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-nonce', nonce);

  // Req 15.1 — Content-Security-Policy with per-request nonce.
  response.headers.set('Content-Security-Policy', buildCSP(nonce));
  // Req 15.2 — Prevent clickjacking.
  response.headers.set('X-Frame-Options', 'DENY');
  // Req 15.3 — Prevent MIME-type sniffing.
  response.headers.set('X-Content-Type-Options', 'nosniff');
  // Req 15.4 — Referrer policy.
  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  // Req 15.5 — HSTS (only effective over HTTPS; harmless on HTTP).
  response.headers.set(
    'Strict-Transport-Security',
    'max-age=31536000; includeSubDomains',
  );
  // Forward the nonce as a response header as well, for layouts that read it.
  response.headers.set('x-nonce', nonce);

  return response;
}

// ---------------------------------------------------------------------------
// Matcher — which paths trigger this proxy
// ---------------------------------------------------------------------------

export const config = {
  matcher: [
    /*
     * Match every path EXCEPT:
     *  - _next/static  — compiled static assets
     *  - _next/image   — Next.js image optimisation
     *  - favicon.ico, sitemap.xml, robots.txt — standard metadata files
     *  - Common image extensions in the public/ folder
     *
     * Note: Next.js automatically runs this proxy for /_next/data/* routes
     * even when they appear to be excluded, to prevent auth gaps.
     */
    '/((?!_next/static|_next/image|favicon\\.ico|sitemap\\.xml|robots\\.txt|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico)$).*)',
  ],
};
